### ISSUE TITLE
Check for amount of training data

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#106] opened 2022-07-20 01:17 UTC
This is related to #36 and #53.

We should add a `check_training_nobs()` or some such name.

Desired behaviour:
* Examine the recipe. At bake time, see if we have at least `nobs` without NAs.
* If we don't have enough data, do something to `predict()` so that it outputs the right number of rows for the target as well as the right columns, but with all NA predictions. So if your frosting creates a `.pred` and a .`pred_distn` column, those would exist, but contain NAs.

A complication here is that, if everything above works, calling `layer_naomit()` would result in an empty `epi_df`. This should NOT happen.

See also #107 .

**Comment by dsweber2** [comment] 2023-08-05 00:32
Just want to note that figuring out that this was the problem I was having took ~a day. The specific case I hit was no training obs that were `ahead` days ahead while also having the max of `lags` days behind (caused by `epix_slide` rounding down rather than up in the number of days it gave us, but that's a topic for somewhere else). Would definitely be useful!

**Comment by dshemetov** [comment] 2024-01-22 23:20
Closed by #283. Can reopen if we find unaddressed edge cases.

**Closed by dshemetov** 2024-01-22 23:20 UTC
Labels: P1
