### ISSUE TITLE
Find long-term solution to `as_tibble.epi_df`

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epipredict#51] opened 2022-06-14 22:51 UTC
As Logan and I found in #49, care must be taken with how we write `as_tibble.epi_df`. 

The tradeoffs are as follows:
- if `as_tibble.epi_df` doesn't remove metadata, then it doesn't actually convert the class to a tibble, which causes an infinite loop inside `dplyr::dplyr_col_modify`
  - furthermore, it's confusing design to have a function named `as_tibble` not actually return a tibble
- if `as_tibble.epi_df` does remove metadata, then we have the issue of losing `epi_df` information every time we use, for instance, `epi_df %>% group_by() %>% mutate()`

Possible solutions are:
- find where `dplyr` uses `as_tibble`, e.g. `mutate` and add S3 alternatives for those
- ?

**Comment by brookslogan** [comment] 2022-06-16 17:44
In addition, when we implement a solution here, the S3 implementation should be migrated from `epipredict` to `epiprocess`.

`epiprocess` already has several dplyr S3 overrides to keep the metadata.  I suspect that this `as_tibble` implementation might actually be unnecessary if `epiprocess` is actually loaded.  But somehow I have been able to run `epipredict` tests without having `epiprocess` installed or loaded.  I suspect maybe this happened with someone else and caused the metadata-dropping issue, so the `as_tibble.epi_df` was added.  (Incidentally, some combination(s) of not having `epipredict` or `epiprocess` loaded actually would "fix" the infinite recursion encountered in #49.)  So really the first possible solution mentioned up above may actually be to make sure `epiprocess` is properly loaded whenever we are using `epi_df`s.

**Comment by dajmcdon** [comment] 2022-06-20 21:43
This was my doing. The issue is that `as_tibble()` gets called way down in `tidymodels` packages. So if we pass in an `epi_df`, eventually (in hard to anticipate places), it gets converted to a tibble and the metadata gets stripped. This makes it hard to implement forecasting in the tidymodels framework when we want to key on the metadata. 

Long term, I'm ok with having the function here (with comments that explain the issue) as long as it "works" and it's not user-facing. It's not needed in `epiprocess` AFIK, just with the prediction.

**Comment by dajmcdon** [comment] 2022-06-20 21:45
Sounds like I need to drop in a test that throws an error without this (potentially troublesome) conversion.

**Comment by dshemetov** [comment] 2022-06-21 17:33
So I think what we're doing now in `as_tibble.epi_df` is just stripping off any `group_by` class, but otherwise doing nothing. I'm not familiar with common practices in R when it comes to `as_type` functions. Is it common to just surface the `type` in the object's classes or is it expected that you remove other classes as well?

Like, I'm thinking that intuitively it's probably bad to have a function that's called `as_tibble` and have it just remove names from the `class` list, but keep a bunch of extra data that tibbles normally don't right?

On the other hand, we don't really have other option than to do this, if we plan to use `tidymodels`?

If we're going to do the latter, should we try to anticipate some issues that might arise when someone expects to use a bare tibble, but instead receives a tibble WITH epi_df metadata, but without the epi_df class marker?

**Comment by dshemetov** [comment] 2022-06-22 20:21
I follow all that and understand that we need some way to intercept calls to `as_tibble` deep in `tidymodels` in a way that doesn't remove `epi_df` metadata.

My questions were more directed at what _exactly_ should `as_tibble.epi_df` do. Doing nothing in that function lead to an infinite regress in `dplyr::mutate` when the `epi_df` was run through `group_by`, because `dplyr::mutate` relied on an `as_tibble` call to strip off the `group_by` class. So right now `as_tibble.epi_df` strips off `group_by` from the passed-in object. 

This was just hotfix that got our tests to pass. I'm now trying to anticipate future issues. 
- should it do anything else? e.g. should it strip off _all_ classes except for `epi_df` and `tibble`?
- are there other unintended side-effects of removing other classes/not removing them?

And case in point, I didn't have to go far to find another issue. In trying to answer questions for this reply, I found that [this line in a basic epiprocess vignette](https://github.com/cmu-delphi/epiprocess/blob/fdf0a49af109d413e78571387c1c21ffa025d939/vignettes/epiprocess.Rmd#L88) gives the error
```
Error: C stack usage  7972948 is too close to the limit
```
which is the exact same error we had when there was an infinite regress of calls that started this issue.

**Comment by dajmcdon** [comment] 2022-06-22 20:52
Ah, ok I see. 

* Probably not helpful, but this particular issue is really ``head()-> head.matrix() -> `[.tbl_df` ``, so it should hopefully be fixed by cmu-delphi/epiprocess#105 (see the review from earlier today).
* I'm surprised that it's the `grouped_df` that causes the problem. I can only assume that there are other possibilities that we haven't encountered.


So to Summarize: long term we need
1. To kill `as_tibble.epi_df` or to have it actually convert to a `tibble`.
2. Some way to ensure that functions in other packages that somewhere nest `as_tibble()` don't also strip the metadata.

These two seem to be at counter purposes.

**Comment by dshemetov** [comment] 2022-06-22 21:44
To be precise about the exact loop we saw for the OP issue, it was in this function
```r
debugging in: dplyr_col_modify.grouped_df(as_tibble(data), cols)
debug: {
    out <- dplyr_col_modify(as_tibble(data), cols)
    if (any(names(cols) %in% group_vars(data))) {
        grouped_df(out, group_vars(data), drop = group_by_drop_default(data))
    }
    else {
        new_grouped_df(out, group_data(data))
    }
}
```
The loop is `dplyr_col_modify -> dplyr_col_modify.grouped_df -> dplyr_col_modify -> ...` when `as_tibble` doesn't remove `grouped_df` from `data`.

**Comment by dajmcdon** [comment] 2022-06-22 22:16
My current plan is to try to intervene in the `fit` process earlier. That way we can avoid the creation of the poorly named `as_tibble.epi_df` completely. If this works, then we can kill that function (until it pops up again elsewhere).

**Comment by brookslogan** [comment] 2022-06-23 17:02
Agree with the plan above to try to eliminate this implementation.

(
One note in case we're not able to eliminate it: we'd want to try to isolate it better (not sure if this is possible with S3) or still consider moving to `epiprocess`.  With the current setup, behavior of `tibble::as_tibble` on `epi_df`s changes based on whether or not `epipredict` is loaded.
<details> <summary>example</summary>

```
edf = as_epi_df(tibble::tibble(geo_value="az",time_value=as.Date("2020-01-01")+0:4,value=1:5))
> edf %>% tibble::as_tibble()
# A tibble: 5 × 3
  geo_value time_value value
  <chr>     <date>     <int>
1 az        2020-01-01     1
2 az        2020-01-02     2
3 az        2020-01-03     3
4 az        2020-01-04     4
5 az        2020-01-05     5
> devtools::load_all("../epipredict", export_all=FALSE)
ℹ Loading epipredict
> edf %>% tibble::as_tibble()
An `epi_df` object, with metadata:
* geo_type  = state
* time_type = day
* as_of     = 2022-06-23 09:55:34

# A tibble: 5 × 3
  geo_value time_value value
* <chr>     <date>     <int>
1 az        2020-01-01     1
2 az        2020-01-02     2
3 az        2020-01-03     3
4 az        2020-01-04     4
5 az        2020-01-05     5
```
</details>
)

**Comment by dajmcdon** [comment] 2022-06-23 17:05
've removed the offending function in #65 and implemented a fix.

I'm going to go ahead and close this issue, but I can foresee it cropping up again. And the removal is a bit cludgy. I put in a few tests to try to catch it directly if someone messes with `hardhat`, but who can say. It's a big pain to handle

**Closed by dajmcdon** 2022-06-23 17:05 UTC
Labels: bug, help wanted
